import {EventBoundary} from 'pixi.js';
import {Suite, assertThat} from '../../TestUtil.js';
import {DisplayView} from '../../draw/scene/TestDisplayView.js';
import {CircuitViewState} from '../../../src/editor/state/CircuitViewState.js';
import {PointerInteractionState} from '../../../src/editor/interaction/PointerInteractionState.js';
import {CircuitDefinition} from '../../../src/circuit/model/CircuitDefinition.js';
import {renderCircuitTargets} from '../../../src/editor/interaction/CircuitTargets.js';
import {Gates} from '../../../src/gates/AllGates.js';
const suite = new Suite('CircuitTargets');
suite.test('Pixi resolves gate edges and initial-state regions and retains targets across pointer updates', async () => {
    const definition = CircuitDefinition.fromTextDiagram(new Map([['B', Gates.Displays.BlochSphereDisplay]]), 'B');
    const circuit = CircuitViewState.empty(20).withCircuit(definition);
    const geometry = circuit.geometry();
    const canvas = document.createElement('canvas');
    canvas.width = 1000; canvas.height = 500;
    const view = new DisplayView(canvas);
    renderCircuitTargets(view, {definition, geometry}, PointerInteractionState.EMPTY);
    await view.commit();
    const boundary = new EventBoundary(view.native);
    const rect = geometry.gateDrawRect(0, 0, Gates.Displays.BlochSphereDisplay);
    const gate = boundary.hitTest(rect.x + 1, rect.center().y);
    assertThat(gate.circuitTarget.type).isEqualTo('gate');
    const ket = geometry.wireInitialStateRect(0).center();
    assertThat(boundary.hitTest(ket.x, ket.y).circuitTarget.type).isEqualTo('initial');
    view.begin();
    renderCircuitTargets(view, {definition, geometry}, PointerInteractionState.EMPTY.withPos(ket));
    await view.commit();
    assertThat(new EventBoundary(view.native).hitTest(rect.x + 1, rect.center().y) === gate).isEqualTo(true);
});
