import { domFor } from './dom.js';

export function dockPropertiesFor(scheme) {
    const d = domFor(scheme);
    return Object.freeze({
        "--dv-paneview-active-outline-color": d["--ring"],
        "--dv-tabs-and-actions-container-font-size": "13px",
        "--dv-tabs-and-actions-container-height": "35px",
        "--dv-drag-over-background-color": d["--focus-shadow"],
        "--dv-drag-over-border-color": d["--ring"],
        "--dv-edge-dock-indicator-color": d["--ring"],
        "--dv-tabs-container-scrollbar-color": d["--sidebar-scrollbar"],
        "--dv-icon-hover-background-color": d["--accent"],
        "--dv-floating-box-shadow": `0 8px 32px ${d["--shadow-popup"]}`,
        "--dv-floating-border": `1px solid ${d["--control-border"]}`,
        "--dv-overlay-z-index": "999",
        "--dv-tab-font-size": "inherit",
        "--dv-border-radius": "0px",
        "--dv-tab-margin": "0",
        "--dv-active-sash-transition-duration": "0.1s",
        "--dv-active-sash-transition-delay": "0.5s",
        "--dv-spacing-padding": "0px",
        "--dv-tab-border-radius": "0px",
        "--dv-sash-border-radius": "0px",
        "--dv-dropdown-border-radius": "0px",
        "--dv-tab-close-icon-size": "inherit",
        "--dv-floating-group-border": "none",
        "--dv-drag-over-border": "none",
        "--dv-floating-group-dragging-opacity": "0.5",
        "--dv-floating-titlebar-height": "22px",
        "--dv-floating-titlebar-background-color": d["--card"],
        "--dv-floating-titlebar-border-bottom": `1px solid ${d["--control-border"]}`,
        "--dv-group-view-background-color": d["--card"],
        "--dv-tabs-and-actions-container-background-color": d["--background"],
        "--dv-activegroup-visiblepanel-tab-background-color": d["--card"],
        "--dv-activegroup-hiddenpanel-tab-background-color": d["--background"],
        "--dv-inactivegroup-visiblepanel-tab-background-color": d["--card"],
        "--dv-inactivegroup-hiddenpanel-tab-background-color": d["--background"],
        "--dv-activegroup-visiblepanel-tab-color": d["--foreground"],
        "--dv-activegroup-hiddenpanel-tab-color": d["--muted-foreground"],
        "--dv-inactivegroup-visiblepanel-tab-color": d["--muted-foreground"],
        "--dv-inactivegroup-hiddenpanel-tab-color": d["--muted-foreground"],
        "--dv-tab-divider-color": d["--border"],
        "--dock-tab-icon-size": "14px",
        "--dv-separator-border": d["--border"],
        "--dv-paneview-header-border-color": d["--border"],
        "--dv-context-menu-background-color": d["--card"],
        "--dv-sash-color": d["--border"],
        "--dv-active-sash-color": d["--ring"],
    });
}
