import {dom} from './dom.js';

export const dockProperties = Object.freeze({
  "--dv-paneview-active-outline-color": dom["--ring"],
  "--dv-tabs-and-actions-container-font-size": "13px",
  "--dv-tabs-and-actions-container-height": "35px",
  "--dv-drag-over-background-color": dom["--focus-shadow"],
  "--dv-drag-over-border-color": dom["--ring"],
  "--dv-edge-dock-indicator-color": dom["--ring"],
  "--dv-tabs-container-scrollbar-color": dom["--sidebar-scrollbar"],
  "--dv-icon-hover-background-color": dom["--accent"],
  "--dv-floating-box-shadow": `0 8px 32px ${dom["--shadow-popup"]}`,
  "--dv-floating-border": `1px solid ${dom["--control-border"]}`,
  "--dv-overlay-z-index": "999",
  "--dv-tab-font-size": "inherit",
  "--dv-border-radius": "0px",
  "--dv-tab-margin": "0",
  "--dv-active-sash-transition-duration": "0.1s",
  "--dv-active-sash-transition-delay": "0.5s",
  "--dv-spacing-padding": "0px",
  "--dv-tab-border-radius": "0px",
  "--dv-sash-border-radius": "0px",
  "--dv-dropdown-border-radius": "0px",
  "--dv-tab-close-icon-size": "inherit",
  "--dv-floating-group-border": "none",
  "--dv-drag-over-border": "none",
  "--dv-floating-group-dragging-opacity": "0.5",
  "--dv-floating-titlebar-height": "22px",
  "--dv-floating-titlebar-background-color": dom["--card"],
  "--dv-floating-titlebar-border-bottom": `1px solid ${dom["--control-border"]}`,
  "--dv-group-view-background-color": dom["--card"],
  "--dv-tabs-and-actions-container-background-color": dom["--background"],
  "--dv-activegroup-visiblepanel-tab-background-color": dom["--card"],
  "--dv-activegroup-hiddenpanel-tab-background-color": dom["--background"],
  "--dv-inactivegroup-visiblepanel-tab-background-color": dom["--card"],
  "--dv-inactivegroup-hiddenpanel-tab-background-color": dom["--background"],
  "--dv-activegroup-visiblepanel-tab-color": dom["--foreground"],
  "--dv-activegroup-hiddenpanel-tab-color": dom["--muted-foreground"],
  "--dv-inactivegroup-visiblepanel-tab-color": dom["--muted-foreground"],
  "--dv-inactivegroup-hiddenpanel-tab-color": dom["--muted-foreground"],
  "--dv-tab-divider-color": dom["--border"],
  "--dock-tab-icon-size": "14px",
  "--dv-separator-border": dom["--border"],
  "--dv-paneview-header-border-color": dom["--border"],
  "--dv-context-menu-background-color": dom["--card"],
  "--dv-sash-color": dom["--border"],
  "--dv-active-sash-color": dom["--ring"],
});

