import {Appearance} from '../../appearance/Appearance.js';
import {colourString} from '../../appearance/formats/colour.js';
import {phaseColor} from '../../appearance/formats/phase.js';
import {Typography as typography} from '../../appearance/formats/typography.js';
const background = colourString(Appearance.colours.ui.background);
const foreground = colourString(Appearance.colours.ui.foreground);
const secondary = colourString(Appearance.colours.ui.secondary);
const controlSurface = colourString(Appearance.colours.ui.controlSurface);
const brandInk = colourString(Appearance.colours.ui.brandInk);
const border = colourString(Appearance.colours.ui.border);
const primary = colourString(Appearance.colours.ui.primary);

export const dom = Object.freeze({
  "--forge-range-fill": `color-mix(in srgb, ${foreground} ${Appearance.opacity.forgeRange * 100}%, transparent)`,
  "--border-width": `${Appearance.borders.width.regular}px`,
  "--border-width-strong": `${Appearance.borders.width.strong}px`,
  "--border-width-focus": `${Appearance.borders.width.focus}px`,
  "--radius-small": `${Appearance.borders.radius.small}px`,
  "--radius-medium": `${Appearance.borders.radius.medium}px`,
  "--font-size-root": `${Appearance.typography.size.root}px`,
  "--space-small": `${Appearance.spacing.small}px`,
  "--space-medium": `${Appearance.spacing.medium}px`,
  "--spacing": `${Appearance.spacing.unit / Appearance.typography.size.root}rem`,
  "--layer-preview": "1000",
  "--layer-popover": "1010",
  "--layer-menu": "1020",
  "--text-caption": `${Appearance.typography.size.caption / Appearance.typography.size.root}rem`,
  "--text-small": `${Appearance.typography.size.small / Appearance.typography.size.root}rem`,
  "--text-body": `${Appearance.typography.size.body / Appearance.typography.size.root}rem`,
  "--text-heading": `${Appearance.typography.size.heading / Appearance.typography.size.root}rem`,
  "--text-title": `${Appearance.typography.size.title / Appearance.typography.size.root}rem`,
  "--font-sans": typography.DEFAULT_FONT_FAMILY,
  "--font-mono": typography.MONO_FONT_FAMILY,
  "--table-divider": colourString(Appearance.colours.ui.tableDivider),
  "--transport-surface": colourString(Appearance.colours.ui.transportSurface),
  "--search-muted": colourString(Appearance.colours.text.muted),
  "--search-surface": colourString(Appearance.colours.ui.searchSurface),
  "--focus-shadow": colourString(Appearance.colours.ui.focusShadow),
  "--tile-hover": colourString(Appearance.colours.ui.tileHover),
  "--tile-outline": colourString(Appearance.colours.stroke.guide),
  "--focus-outline": colourString(Appearance.colours.stroke.guide),
  "--inset-surface": secondary,
  "--sidebar-muted": colourString(Appearance.colours.text.muted),
  "--control-border": colourString(Appearance.colours.ui.controlBorder),
  "--control-surface": controlSurface,
  "--control-hover": colourString(Appearance.colours.ui.controlHover),
  "--input-surface": controlSurface,
  "--brand-ink": brandInk,
  "--brand-surface": colourString(Appearance.colours.ui.brandSurface),
  "--brand-border": colourString(Appearance.colours.ui.brandBorder),
  "--brand-glow": colourString(Appearance.colours.ui.brandGlow),
  "--panel-heading": brandInk,
  "--panel-glow": colourString(Appearance.colours.ui.panelGlow),
  "--panel-primary-hover": colourString(Appearance.colours.ui.panelPrimaryHover),
  "--panel-option-surface": colourString(Appearance.colours.ui.panelOptionSurface),
  "--panel-option-border": colourString(Appearance.colours.ui.panelOptionBorder),
  "--panel-link": colourString(Appearance.colours.text.muted),
  "--panel-link-hover": colourString(Appearance.colours.text.primary),
  "--error-border": colourString(Appearance.colours.ui.errorBorder),
  "--sidebar-scrollbar": colourString(Appearance.colours.ui.sidebarScrollbar),
  "--shadow-popup": colourString(Appearance.colours.ui.shadowPopup),
  "--shadow-banner": colourString(Appearance.colours.ui.shadowBanner),
  "--shadow-control": colourString(Appearance.colours.ui.shadowControl),
  "--state-probability-fill": colourString(Appearance.colours.probability.fill),
  "--state-probability-back": colourString(Appearance.colours.probability.background),
  "--operator": colourString(Appearance.colours.operation.fill),
  "--bloch-axis-x": colourString(Appearance.colours.bloch.axisX),
  "--bloch-axis-y": colourString(Appearance.colours.bloch.axisY),
  "--bloch-axis-z": colourString(Appearance.colours.bloch.axisZ),
  "--phase-legend": `linear-gradient(to right, ${Array.from({ length: 9 }, (_, i) => phaseColor(-180 + i * 45)).join(", ")})`,
  "--app-font-sans": typography.DEFAULT_FONT_FAMILY,
  "--app-font-mono": typography.MONO_FONT_FAMILY,
  "--background": background,
  "--foreground": foreground,
  "--card": colourString(Appearance.colours.surface.quiet),
  "--card-foreground": foreground,
  "--popover": colourString(Appearance.colours.surface.quiet),
  "--popover-foreground": foreground,
  "--primary": primary,
  "--primary-foreground": colourString(Appearance.colours.surface.quiet),
  "--secondary": secondary,
  "--secondary-foreground": foreground,
  "--muted": secondary,
  "--muted-foreground": colourString(Appearance.colours.text.muted),
  "--accent": secondary,
  "--accent-foreground": foreground,
  "--destructive": colourString(Appearance.colours.error.text),
  "--border": border,
  "--input": colourString(Appearance.colours.ui.input),
  "--ring": colourString(Appearance.colours.stroke.guide),
  "--radius": `${Appearance.borders.radius.control / Appearance.typography.size.root}rem`,
  "--sidebar": background,
  "--sidebar-foreground": foreground,
  "--sidebar-primary": primary,
  "--sidebar-primary-foreground": colourString(Appearance.colours.surface.quiet),
  "--sidebar-accent": secondary,
  "--sidebar-accent-foreground": foreground,
  "--sidebar-border": border,
  "--sidebar-ring": colourString(Appearance.colours.stroke.guide),
  "--button-ghost-hover": `color-mix(in oklab, ${secondary} ${Appearance.opacity.ghostHover * 100}%, transparent)`,
  "--button-focus-shadow": `color-mix(in oklab, ${colourString(Appearance.colours.stroke.guide)} ${Appearance.opacity.focus * 100}%, transparent)`,
  "--matrix-active-surface": `color-mix(in oklab, ${colourString(Appearance.colours.stroke.guide)} ${Appearance.opacity.matrixActive * 100}%, transparent)`,
  "--operator-control-surface": `color-mix(in oklab, ${foreground} ${Appearance.opacity.operatorControl * 100}%, transparent)`,
});
